# Generated by Django 4.1.7 on 2023-04-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_question_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_difficulty',
            new_name='question_levels',
        ),
    ]
