# Generated by Django 4.2 on 2023-04-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_question_difficulty_question_question_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
